<a href="<?php echo $this->url(array('action' => 'add')); ?>">dodaj</a>

<?php if(!count($this->items)): ?>
	<p>Brak danych</p>
<?php else: ?>
    <table>
        <thead>
            <tr>
                <?php foreach($this->cols as $col): ?>
                    <th><?php echo $col; ?></th>
                <?php endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->items as $item): ?>
            <tr>
                <?php foreach($this->cols as $col): ?>
                    <td><?php echo $item->{$col}; ?></td>
                <?php endforeach; ?>
                <td>
                    <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->id)); ?>">edycja</a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item->id)); ?>">usuń</a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
    